layers:
  external_systems:
    name: "External Systems"
    top_left_x: 0
    top_left_y: -160  
    nof_cols: 2
    nof_rows: 10      
    building_blocks:
      - crm:
        name: "CRM"
  governance_management:
    name: "Governance & Management"
    top_left_x: 0
    top_left_y: -160
    nof_cols: 10
    nof_rows: 1
    align_left_with: external_systems
    building_blocks:
      - data-catalog:
        name: "Data Catalog"
      - event-catalog:
        name: "Event Catalog"
      - api-catalog:
        name: "API Catalog"
      - api-management:
        name: "API Management"
  security_compliance:
    name: "Security & Compliance"
    top_left_x: 0
    top_left_y: -160
    nof_cols: 8
    nof_rows: 1
    align_left_with: governance_management
    building_blocks:
      - iam:
        name: "IAM"
      - secrets-management:
        name: "Secrets Management"
      - key-management:
        name: "Key Management"
      - policy-engine:
        name: "Policy Engine"        
  monitoring_observability:
    name: "Monitoring & Observability"
    top_left_x: 0
    top_left_y: -160
    nof_cols: 6
    nof_rows: 1
    align_left_with: security_compliance
    building_blocks:
      - data-lineage:
        name: "Data Lineage"
      - data-observability:
        name: "Data Observability"
  integration:
    name: "Integration"
    top_left_x: 0
    top_left_y: 0
    nof_cols: 2
    nof_rows: 8
    align_left_with: external_systems
    building_blocks:
      - managed-data-transfer:
        name: "Managed Data/File Transfer"
      - disk-service:
        name: "Disk Service"
      - web-crawler:
        name: "Web Crawler"
      - data-collector:
        name: "Data Collector"
      - batch-data-flow:
        name: "Batch Data Flow"
      - stream-data-flow:
        name: "Stream Data Flow"
      - change-data-capture:
        name: "Change Data Capture"
  batch-driven-apps:
    name: "Batch-Driven Applications"
    top_left_x: 180
    top_left_y: 0
    nof_cols: 15
    nof_rows: 1
    align_left_with: integration
    building_blocks:
      - batch-micro-service:
        name: "Batch (Micro-)Service"            
  request-event-process-driven-apps:
    name: "Request-Driven, Event-Driven and Process-Driven Applications"
    top_left_x: 180
    top_left_y: 560
    nof_cols: 15
    nof_rows: 1
    align_left_with: integration
    building_blocks:
      - backend-micro-service:
        name: "Backend (Micro-)Service"
      - function-as-a-service:
        name: "Function-as-a-Service"
      - low-no-code-apps:
        name: "Low / No Code Apps"
      - stream-data-flow:
        name: "Stream Data Flow"
      - stream-processing:
        name: "Stream Processing"                       
  persistence:
    name: "Data Persistence Services"
    top_left_x: 180
    top_left_y: 160
    nof_cols: 7
    nof_rows: 4
    align_left_with: integration
    building_blocks:
      - event-broker:
        name: "Event Broker"
      - file-storage:
        name: "File Storage"
      - relational-database:
        name: "Relational Database"
      - key-value-store:
        name: "Key-Value Store"
      - timeseries-database:
        name: "Timeseries Database"
      - olap-datastore:
        name: "OLAP Datastore"
      - clinical-data-repository:
        name: "Clinical Data Repository"
      - message-broker:
        name: "Message Broker"
      - distributed-file-system:
        name: "Distributed File System"
      - distributed-sql-database:
        name: "Distributed SQL Database"
      - wide-column-store:
        name: "Wide-Column Store"
      - graph-database:
        name: "Graph Database"
      - vector-database:
        name: "Vector Database"
      - event-store:
        name: "Event Store"
      - object-storage:
        name: "Object Storage"
      - in-memory-database:
        name: "In-Memory Database"
      - document-database:
        name: "Document Database"
      - rdf-store:
        name: "RDF Store"
      - feature-store:
        name: "Feature Store"
      - distributed-ledger:
        name: "Distributed Ledger"
      - document-management:
        name: "Document Management"
      - in-memory-data-grid:
        name: "In-Memory Grid"
      - search-engine-store:
        name: "Search-Engine Store"
      - spatial-database:
        name: "Spatial Database"
      - streaming-database:
        name: "Streaming Database"            
  processing_analysis:
    name: "Processing & Analytics Services"
    top_left_x: 660
    top_left_y: 160
    nof_cols: 7
    nof_rows: 4
    align_left_with: persistence
    building_blocks:
      - format-translation:
        name: "Format Translator"
      - data-validation:
        name: "Data Validator"
      - chatbot:
        name: "Chatbot"
      - machine-learning:
        name: "Machine Learning"
      - image-video-recognition:
        name: "Image & Video Recognition"
      - text-analytics:
        name: "Text Analytics"
      - timeseries-analytics:
        name: "Timeseries Analytics"
  serving:
    name: "Serving"
    top_left_x: 1140
    top_left_y: 0
    nof_cols: 2
    nof_rows: 8
    align_left_with: processing_analysis
    building_blocks:
      - data-science-workbench:
        name: "Data Science Workbench"

mappings:
  event-broker:
    - aws.mks
    - aws.kinesis
              